server:
  port: 8080

spring:
  application:
    name: App
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/app?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    password:
    database: 0
    redisson:
      file: classpath:redisson.yml


mybatis-plus:
  mapper-locations: /mapper/*Mapper.xml


thread:
  pool:
    corePoolSize: 5
    maxPoolSize: 8
    queueCapacity: 20
    keepAliveSeconds: 30